version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true

# Optionally set the version of Python and requirements required to build your docs
python:
    install:
      - method: pip
        path: .
        extra_requirements:
         - docs
