version: 2

# conda:
#     environment: install/environment.yml

sphinx:
    configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
    version: 3.7
    install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
        extra_requirements:
         - docs
    system_packages: true