name: emulators
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.8
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.12.0
  - scikit-learn=1.5.1
  - joblib=1.3.2
  - psutil=5.9.8
  - dill=0.3.8
  - pip=24.0
