# config file for spellcheck action
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
    - .github/workflows/.wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/**/*.md'
  default_encoding: utf-8
- name: RST
  sources:
  - '**/**/*.rst'
  dictionary:
    wordlists:
    - .github/workflows/.wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.text:
      convert_encoding: utf-8
